### ISSUE TITLE
Увести создание/подготовку верстки в html

### ISSUE THREAD

**Issue by dustyo-O** [britishpop/britishpop.github.io#1]
Например, картинку
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L24

Просто положи в html. Аналогично во всех подобных случаях

**Comment by britishpop** [comment]
https://github.com/britishpop/britishpop.github.io/commit/cbca01c243f29ec68345c426fb867e3b9eaa4de2
