### ISSUE TITLE
Упростить функции инвертировав if, где это возможно

### ISSUE THREAD

**Issue by dustyo-O** [britishpop/britishpop.github.io#2]
Например, вот тут
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L64

есть сделать if (isWaiting) return;

То все тело функции выйдет из условного оператора.

Аналогично:
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L308
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L322
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L343
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L361
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L378
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L451
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L563
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L580
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L590
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L604
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L617
https://github.com/britishpop/britishpop.github.io/blob/5a4cf77863825876b5559342cb81ffb00e220af6/js/solution.js#L633

может, есть и другие места

**Comment by britishpop** [comment]
https://github.com/britishpop/britishpop.github.io/commit/40f503f83f935f2b1bbe2af1dc5d442bd824a5a1
